import re
from pptx import Presentation
from io import BytesIO

import streamlit as st
from openai import OpenAI

client = OpenAI(
    api_key="api key of yours",
    base_url="https://openrouter.ai/api/v1"
)
def create_ppt(content, topic):
    prs = Presentation()
    # Cover Slide
    cover = prs.slides.add_slide(prs.slide_layouts[0])
    cover.shapes.title.text = topic
    cover.placeholders[1].text = "Generated by SlidesSpawn AI"

    # Split into slides
    slide_sections = re.split(r"(?=Slide\s+\d+:)", content)

    for section in slide_sections:

        section = section.strip()

        if not section:
            continue

        lines = [line.strip() for line in section.split("\n") if line.strip()]

        if len(lines) == 0:
            continue

        title = lines[0]

        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = title

        body = slide.placeholders[1]
        body.text = ""

        first = True

        for line in lines[1:]:

            if line.startswith("-"):
                bullet = line[1:].strip()

                if first:
                    body.text = bullet
                    first = False
                else:
                    p = body.text_frame.add_paragraph()
                    p.text = bullet

    ppt_file = BytesIO()
    prs.save(ppt_file)
    ppt_file.seek(0)

    return ppt_file


st.set_page_config(
    page_title="SlidesSpawn AI",
    page_icon="🚀",
    layout="wide"
)

st.markdown("""
<style>

.stApp {
    background: linear-gradient(135deg, #0f172a, #1e293b);
    color: white;
}

.main-title {
    font-size: 4rem;
    font-weight: 800;
    text-align: center;
    color: white;
    margin-bottom: 0;
}

.sub-title {
    text-align: center;
    color: #94a3b8;
    font-size: 1.1rem;
    margin-bottom: 40px;
}

.glass {
    background: rgba(255,255,255,0.08);
    padding: 25px;
    border-radius: 20px;
    backdrop-filter: blur(12px);
    border: 1px solid rgba(255,255,255,0.1);
}

.stButton > button {
    width: 100%;
    background: linear-gradient(90deg,#7c3aed,#2563eb);
    color: white;
    border: none;
    border-radius: 12px;
    padding: 15px;
    font-size: 18px;
    font-weight: bold;
}

.stButton > button:hover {
    transform: scale(1.02);
}

</style>
""", unsafe_allow_html=True)

# ---------- HERO ----------
st.markdown(
    "<h1 class='main-title'>🚀 SlidesSpawn AI</h1>",
    unsafe_allow_html=True
)

st.markdown(
    "<p class='sub-title'>Generate beautiful presentations in seconds using AI</p>",
    unsafe_allow_html=True
)

# ---------- LAYOUT ----------
left, right = st.columns([2,1])

with left:

    st.markdown("<div class='glass'>", unsafe_allow_html=True)

    topic = st.text_input(
        "Presentation Topic",
        placeholder="e.g. Artificial Intelligence in Healthcare"
    )

    slides = st.slider(
        "Number of Slides",
        min_value=3,
        max_value=15,
        value=5
    )

    st.markdown("</div>", unsafe_allow_html=True)

with right:

    st.markdown("<div class='glass'>", unsafe_allow_html=True)

    presentation_type = st.selectbox(
        "Presentation Type",
        [
            "College",
            "Business",
            "Marketing",
            "Seminar"
        ]
    )

    generate = st.button("✨ Generate Presentation")

    st.markdown("</div>", unsafe_allow_html=True)

# ---------- GENERATE ----------
if generate:

    if not topic:
        st.warning("Please enter a topic.")

    else:

        with st.spinner("🧠 AI is building your presentation..."):

            prompt = f"""
Create a professional PowerPoint presentation.

Topic: {topic}
Type: {presentation_type}

Generate exactly {slides} slides.

Return ONLY in this format:

Slide 1: Title
- Bullet point
- Bullet point
- Bullet point
- Bullet point

Slide 2: Title
- Bullet point
- Bullet point
- Bullet point
- Bullet point

Continue until all {slides} slides are generated.
"""
            response = client.chat.completions.create(
    model="openai/gpt-3.5-turbo",
    messages=[
        {
            "role": "user",
            "content": prompt
        }
    ]
)

            

        output = response.choices[0].message.content
        ppt_file = create_ppt(output, topic)    

        st.success("Presentation Generated!")

        st.markdown("## 📑 Generated Slides")

        st.markdown(
            f"""
            <div class='glass'>
            {output}
            </div>
            """,
            unsafe_allow_html=True
        )
        st.download_button(
    label="📥 Download PPTX",
    data=ppt_file,
    file_name=f"{topic}.pptx",
    mime="application/vnd.openxmlformats-officedocument.presentationml.presentation"
)